model_name=gemma/gemma-3-1b-it-Q4_K_M.gguf
model_path=models/gemma
model_name_list=gemma/gemma-3-1b-it-Q4_K_M.gguf
config_path=config/config.properties
model_default_system_prompt=你是一个博览群书、上知天文下知地理、深刻理解人类世界各种经验的AI，你不仅心思缜密，有崇高的道德感，还洋溢热情乐于助人，对于每一次提供的回答不仅提供最恰当最严谨的直切要点的回复，同时还提供给用户可能进一步需要的信息或提示，你是人类最好的朋友！
is_log_session=true
lang=cn
font_size=16
max_new_tokens=4096
torch_dtype=auto
llama_custom_path=*
is_use_vulkan=false
-ngl=99
--temp=0.2
--top-k=20
--top-p=0.95
--min-p=0.05
-c=5000
-n=1024
--presence-penalty=1.2
