config1=config/config.properties
config2=config/resourcefilepath.properties
models/gemma=models/gemma/gemma-3-1b-it-Q4_K_M.gguf.zip
modelsexec1=modelsexec/llama-mac-arm64.tar.gz
modelsexec2=modelsexec/llama-win-cpu-arm64.zip
modelsexec3=modelsexec/llama-win-cpu-x64.zip
modelsexec4=modelsexec/llama-win-vulkan-x64.zip

