chatWindow=会话窗口
help=帮助
LanguageSwitch=The language switch will take effect the next time you open the app.
fontSize=字体大小
send=发送
newChat=新对话
chatInExplorer=在浏览器中和AI对话
thinkingMode=思考模式
openChatLog=打开对话记录
tips=使用建议
productIntroduction=产品介绍
productSlogan=开源，100%离线使用，免费
model=模型
saveConversation=保存对话