chatWindow=Chat Window
help=Help
LanguageSwitch=下次打开应用程序时，语言切换将生效。
fontSize=Font Size
send=Send
newChat=New Chat
chatInExplorer=Chat In Explorer
thinkingMode=thinking
openChatLog=Open Chat Log
tips=Tips
productIntroduction=Product Introduction
productSlogan=Open source, 100% offline, free
model=model
saveConversation=Save Conversation